package proyecto;

 

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
// Importamos java.net.URL para poder usar getResource()
import java.net.URL; 

public class LoginView extends javax.swing.JFrame {

    // Variable para el logo
    private javax.swing.JLabel lblLogo;

    /**
     * Creates new form LoginView
     */
        
        public LoginView() {
        initComponents();
        
        // --- ARREGLO IMPORTANTE ---
        // Esta línea mueve nuestro panel de login a la capa superior ("Modal")
        // para que se dibuje ENCIMA del fondo (que está en "Default Layer").
        getLayeredPane().add(panelLogin, JLayeredPane.MODAL_LAYER);
        // --- FIN DEL ARREGLO ---
        
        
        // --- NUESTRAS MODIFICACIONES ---
        
        // 1. Establecer el tamaño de la ventana
        setSize(800, 800);
        
        // 2. Centrar la ventana en la pantalla
        setLocationRelativeTo(null);
        
        // 3. Llamar a nuestro método para configurar el fondo
        configurarFondo();
        
        // 4. Llamar al método para configurar el logo
        configurarLogo();
        
        // 5. Hacer que nuestro panel de login sea semitransparente
        // (El '220' es el nivel de alfa/transparencia. 255=sólido, 0=invisible)
        panelLogin.setBackground(new Color(255, 255, 255, 220));
        
        // --- FIN DE MODIFICACIONES ---
    }
    
    /**
     * Método para configurar la imagen de fondo (Cargando desde SRC).
     */
    private void configurarFondo() {
        // --- ¡¡¡IMPORTANTE 1!!! ---
        // Asegúrate de que esta ruta sea correcta.
        String rutaImagen = "/assets/fondo.jpg"; 
        // -------------------------

        try {
            // Obtenemos la URL del recurso que está DENTRO del JAR
            URL urlFondo = getClass().getResource(rutaImagen);

            if (urlFondo == null) {
                // Esto pasa si la ruta está mal escrita
                throw new Exception("Recurso de fondo no encontrado: " + rutaImagen);
            }
            
            ImageIcon icono = new ImageIcon(urlFondo);

            // Escalar la imagen
            Image img = icono.getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon iconoEscalado = new ImageIcon(img);
            JLabel fondoLabel = new JLabel(iconoEscalado);
            fondoLabel.setBounds(0, 0, this.getWidth(), this.getHeight());

            // Añadir el JLabel al JLayeredPane (detrás de todo)
            getLayeredPane().add(fondoLabel, JLayeredPane.DEFAULT_LAYER);

            // Hacer que el panel de contenido sea transparente
            ((JPanel)getContentPane()).setOpaque(false);
            
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen de fondo: " + e.getMessage());
             getContentPane().setBackground(Color.DARK_GRAY);
        }
    }

    /**
     * Método para configurar el logo (Cargando desde SRC).
     */
    private void configurarLogo() {
        // --- ¡¡¡IMPORTANTE 2!!! ---
        // Asegúrate de que esta ruta sea correcta.
        String rutaLogo = "/assets/dojo.png";
        int logoAncho = 128; 
        int logoAlto = 128; 
        // -------------------------

        try {
            // Obtenemos la URL del recurso
            URL urlLogo = getClass().getResource(rutaLogo);
            
            if (urlLogo == null) {
                throw new Exception("Recurso de logo no encontrado: " + rutaLogo);
            }
            
            ImageIcon iconoLogo = new ImageIcon(urlLogo);
            
            Image img = iconoLogo.getImage().getScaledInstance(logoAncho, logoAlto, Image.SCALE_SMOOTH);
            // Asignamos la imagen al JLabel 'lblLogo'
            lblLogo.setIcon(new ImageIcon(img));
            
        } catch (Exception e) {
            System.err.println("Error al cargar el logo: " + e.getMessage());
            lblLogo.setText("[ LOGO NO ENCONTRADO ]"); 
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Dojo - Login");
        setResizable(false);

        panelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("ADMINISTRACIÓN DE DOJO");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsuario.setText("Usuario:");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUsuario.setText("admin");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPassword.setText("Contraseña:");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPassword.setText("123");

        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario)
                            .addComponent(txtPassword))))
                .addGap(40, 40, 40))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addGap(20, 20, 20)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // LÓGICA DE INICIO DE SESIÓN
        String usuario = txtUsuario.getText();
        String pass = new String(txtPassword.getPassword());

        // SIMULACIÓN DE ÉXITO:
        if (usuario.equals("admin") && pass.equals("123")) {
            
            // Abrir la ventana principal
            // (Asegúrate de tener un MainView.java)
      //      MainView menuPrincipal = new MainView();
      //      menuPrincipal.setVisible(true);
            
            // Cerrar esta ventana de Login
            this.dispose(); 
            
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error de Login", JOptionPane.ERROR_MESSAGE);
        }
    }                                                

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // Aquí llamarías a tu JDialog de Registro
        // Ejemplo:
        // RegistroView dialog = new RegistroView(this, true);
        // dialog.setVisible(true);
        
        JOptionPane.showMessageDialog(this, "Aquí se abriría la ventana de registro.");
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    // 'lblLogo' se declara arriba
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration                   
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
