// Asegúrate de que esto coincida con tu paquete
package proyecto;

// Importamos el LoginView para poder volver a él
import proyecto.LoginView;
import javax.swing.JOptionPane;

public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
   public MainView() {
        initComponents(); // Carga el diseño

        // --- !!! ARREGLO DEFINITIVO !!! ---
        // Esto le dice al MainView: "Si te cierran, solo desaparece (dispose)"
        // ANULA el "EXIT_ON_CLOSE" que está en initComponents()
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        // --- FIN DEL ARREGLO ---
        
        // --- Tus otras modificaciones ---
        this.setExtendedState(MAXIMIZED_BOTH);
        escritorioPrincipal.setBackground(new java.awt.Color(45, 45, 45));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        escritorioPrincipal = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        menuGestion = new javax.swing.JMenu();
        itemGestionEstudiantes = new javax.swing.JMenuItem();
        itemGestionRepresentantes = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenu();
        itemVerHistorial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal - Sistema de Administración de Dojo");

        // Configuración del JDesktopPane
        escritorioPrincipal.setBackground(new java.awt.Color(45, 45, 45));
        javax.swing.GroupLayout escritorioPrincipalLayout = new javax.swing.GroupLayout(escritorioPrincipal);
        escritorioPrincipal.setLayout(escritorioPrincipalLayout);
        escritorioPrincipalLayout.setHorizontalGroup(
            escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        escritorioPrincipalLayout.setVerticalGroup(
            escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        // --- Configuración del Menú ---
        
        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemCerrarSesion.setText("Cerrar Sesión");
        itemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarSesionActionPerformed(evt);
            }
        });
        menuArchivo.add(itemCerrarSesion);

        itemSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(itemSalir);

        menuBar.add(menuArchivo);

        menuGestion.setText("Gestión");
        menuGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemGestionEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionEstudiantes.setText("Estudiantes");
        itemGestionEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionEstudiantesActionPerformed(evt);
            }
        });
        menuGestion.add(itemGestionEstudiantes);

        itemGestionRepresentantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGestionRepresentantes.setText("Representantes");
        itemGestionRepresentantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionRepresentantesActionPerformed(evt);
            }
        });
        menuGestion.add(itemGestionRepresentantes);

        menuBar.add(menuGestion);

        menuHistorial.setText("Historial");
        menuHistorial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemVerHistorial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemVerHistorial.setText("Exámenes y Certificados");
        itemVerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerHistorialActionPerformed(evt);
            }
        });
        menuHistorial.add(itemVerHistorial);

        menuBar.add(menuHistorial);

        setJMenuBar(menuBar);

        // Layout principal del JFrame
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPrincipal) // El escritorio ocupa todo
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPrincipal) // El escritorio ocupa todo
        );

        pack();
    }// </editor-fold>                        

    
    // --- EVENTOS DE LOS BOTONES DEL MENÚ ---
    
    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // Cierra esta ventana (MainView)
        this.dispose();
        
        // Vuelve a abrir el Login (asumiendo que se llama LoginView.java)
        LoginView login = new LoginView();
        login.setVisible(true);
    }                                                

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Cierra toda la aplicación
        System.exit(0);
    }                                         

    private void itemGestionEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // --- TU PRÓXIMO PASO ---
        // 1. Crea un "JInternalFrame Form" llamado "EstudiantesView.java"
        // 2. Descomenta las siguientes 3 líneas:
        
        // EstudiantesView vistaEstudiantes = new EstudiantesView();
        // escritorioPrincipal.add(vistaEstudiantes);
        // vistaEstudiantes.setVisible(true);
        
        JOptionPane.showMessageDialog(this, "Aún no has creado la vista 'EstudiantesView'");
    }                                                      

    private void itemGestionRepresentantesActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // 1. Crea un "JInternalFrame Form" llamado "RepresentantesView.java"
        // 2. Descomenta las siguientes 3 líneas:
        
        // RepresentantesView vistaRepresentantes = new RepresentantesView();
        // escritorioPrincipal.add(vistaRepresentantes);
        // vistaRepresentantes.setVisible(true);
        
        JOptionPane.showMessageDialog(this, "Aún no has creado la vista 'RepresentantesView'");
    }                                                         

    private void itemVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // 1. Crea un "JInternalFrame Form" llamado "HistorialView.java"
        // 2. Descomenta las siguientes 3 líneas:
        
        // HistorialView vistaHistorial = new HistorialView();
        // escritorioPrincipal.add(vistaHistorial);
        // vistaHistorial.setVisible(true);
        
        JOptionPane.showMessageDialog(this, "Aún no has creado la vista 'HistorialView'");
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JDesktopPane escritorioPrincipal;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemGestionEstudiantes;
    private javax.swing.JMenuItem itemGestionRepresentantes;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemVerHistorial;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenu menuHistorial;
    // End of variables declaration                   
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
